### PR TITLE
clean up the structure

### PR DESCRIPTION
**Pull request by zaherg**
clean up the structure

clean up the structure

clean up the structure a bit

feel free not to accept it, as this is just a personal preferences

### CODE REVIEW

**Comment by chrissmejia** [comment]
Hi @linuxjuggler, sorry I was coding a huge test for a new job, sadly, is hard to live coding Open Source jeje.

I take a look to the commit and I agree with you, I feel more conformable with the way you write the code, but that's not the convention, I shock too but the recommended indentation is 2 spaces then I think we need to follow that convention, even I'm starting to use in my projects.

I leave you some links about.

http://www.w3schools.com/html/html5_syntax.asp (Blank Lines and Indentation)
http://stackoverflow.com/questions/2678817/2-spaces-or-1-tab-whats-the-standard-for-indentation-in-the-rails-community
http://stackoverflow.com/questions/2167524/do-you-indent-your-html-code
https://google.github.io/styleguide/htmlcssguide.xml (General Formatting Rules)

Thanks again for your job.

**Comment by zaherg** [comment]
hi @chrissmejia , the discussion between spaces and tabs will never end to be honest, but in general and thats what I go for , is for readability .

thanks for the links, and I will check it and try to follow the most common one .

have a nice coding and thanks for this nice project

**Comment by chrissmejia** [comment]
Hi @linuxjuggler yes is a never end jeje.

Thanks a lot for your contributions, is a big project and is hard to accomplish alone, is not only the html, at some point actually dashboards based on this will be created, probably on php and django, then you can have all common features there for you, you only need some custom code to show your data or wherever you want to do with it.

**Comment by zaherg** [comment]
am already integrating your dashboard in a small open source project am building using Laravel Lumen micro framework . 

wish you all the best

**Comment by chrissmejia** [comment]
Oh men that's awesome, you are working faster than me jajaja, feel free to share the base to other projects if you want, I don't have that much experience on modern php I've been reading the Modern PHP book, but there's so much things different now.

I will be glad to link your project to the site and repository.

All the best for you too.

**Comment by zaherg** [comment]
nah, am not that fast esp with too much load from work . once I finish it I will share the link with you for sure.

Modern php is great as a reference for best practice not to learn any new modern framework ( at least the part which I read from it till today ) , but if you want to learn about laravel for example you can check 
1- http://laracasts.com/all 
2- http://s.zah.me/1DESNfH list of books about laravel
3- http://s.zah.me/1KUzTSZ list of books about php in general

thanks

**Comment by chrissmejia** [comment]
Jajaja that happens, thanks, is good to know your effort is useful :)

Yes I'm actually shock because there's a lot of companies out there with a new paradigm, don't marry any framework, just use the modules they need from each, that's new for me.

I actually bought "Laravel 5 Essentials" too, I'm going to read it if I found a job en php or when have to code this for php, thank you so much for the references, I'm definitely going to take a look.

**Pull request closed without merging**
